spring.profiles.active=test

spring.datasource.url=jdbc:mysql://localhost:3306/sporting_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
server.port=8081
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-post-size=50MB
server.tomcat.max-swallow-size=50MB
spring.main.allow-bean-definition-overriding=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

app.jwt.secret=ThisIsAStrongAndSecureSecretKeyForSportingShopApplicationPleaseChangeIt
app.jwt.expiration-ms=86400000

app.gemini.api-key=${GEMINI_API_KEY:AIzaSyAvDeN0OXkqJoi-Ue88Pi8UQ24R91WeSPA}
app.gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

spring.config.import=optional:file:.env.properties